# 认证请求状态
AUTH_REQ_STATUS_WAITING = 0
AUTH_REQ_STATUS_PASSED = 1
AUTH_REQ_STATUS_DENIED = 2

AUTH_REQ_STATUSES = [
    (AUTH_REQ_STATUS_WAITING, "等待审批"),
    (AUTH_REQ_STATUS_PASSED, "认证通过"),
    (AUTH_REQ_STATUS_DENIED, "认证失败"),
]

# 商品状态
COMM_STATUS_INVALID = 0
COMM_STATUS_PRE_SELL = 1
COMM_STATUS_ON_SELL = 2
COMM_STATUS_CLOSED = 3

COMM_STATUSES = [
    (COMM_STATUS_INVALID, "商品未生效"),
    (COMM_STATUS_PRE_SELL, "商品预售中"),
    (COMM_STATUS_ON_SELL, "商品售卖中"),
    (COMM_STATUS_CLOSED, "商品已下架"),
]

# 订单状态
ORDER_STATUS_ORDERED = 0
ORDER_STATUS_PAID = 1
ORDER_STATUS_DELIVERED = 2
ORDER_STATUS_CONFIRMED = 3
ORDER_STATUS_COMMENTED = 4
ORDER_STATUS_CLOSED = 5

ORDER_STATUS_DICT = {ORDER_STATUS_ORDERED: "已下单", ORDER_STATUS_PAID: "已支付", ORDER_STATUS_DELIVERED: "已发货",
                     ORDER_STATUS_CONFIRMED: "已确认收货", ORDER_STATUS_COMMENTED: "已评价", ORDER_STATUS_CLOSED: "已关闭"}

ORDER_STATUSES = [
    (ORDER_STATUS_ORDERED, "已下单"),
    (ORDER_STATUS_PAID, "已支付"),
    (ORDER_STATUS_DELIVERED, "已送达"),
    (ORDER_STATUS_CONFIRMED, "已确认"),
    (ORDER_STATUS_COMMENTED, "已评价"),
    (ORDER_STATUS_CLOSED, "已关闭"),
]
