# Generated by Django 4.1.2 on 2022-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity", name="sale", field=models.IntegerField(default=0),
        ),
    ]
