# Generated by Django 4.1.2 on 2022-11-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_alter_commodity_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trade.image",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="para_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trade.paraset"
            ),
        ),
        migrations.AlterField(
            model_name="paraset",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trade.commodity"
            ),
        ),
    ]
