# Generated by Django 4.1.2 on 2022-11-20 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_commodity_image_alter_parameter_para_set_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("oss_token", models.CharField(max_length=300)),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveField(model_name="image", name="image_dem",),
        migrations.RemoveField(model_name="comment", name="image_dem",),
        migrations.RemoveField(model_name="commodity", name="image_dem",),
        migrations.AddField(
            model_name="order",
            name="deliver_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(name="ImageDem",),
        migrations.AddField(
            model_name="comment",
            name="image_set",
            field=models.ManyToManyField(to="trade.file"),
        ),
        migrations.AddField(
            model_name="commodity",
            name="image_set",
            field=models.ManyToManyField(to="trade.file"),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_image",
                to="trade.file",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="trade.file"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="trade.file"
            ),
        ),
        migrations.DeleteModel(name="Image",),
    ]
