# Generated by Django 4.1.2 on 2022-11-20 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_file_remove_image_image_dem_remove_comment_image_dem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuauthreq",
            name="image",
            field=models.ForeignKey(
                default=23, on_delete=django.db.models.deletion.PROTECT, to="trade.file"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="type",
            field=models.IntegerField(choices=[(0, "个人店铺"), (1, "合作店铺")]),
        ),
        migrations.DeleteModel(name="ShopAuthReq",),
    ]
