# Generated by Django 4.1.2 on 2022-11-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_stuauthreq_image_alter_shop_type_delete_shopauthreq"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
    ]
