# Generated by Django 4.1.2 on 2022-11-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0006_delete_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleop",
            name="op",
            field=models.IntegerField(choices=[(0, "赞"), (1, "收藏")]),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="image",
            field=models.ForeignKey(
                default=17,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="main_image",
                to="trade.file",
            ),
            preserve_default=False,
        ),
    ]
